const { test } = require('node:test');
const assert = require('node:assert/strict');
const { WebSocket } = require('ws');
const { once } = require('node:events');
const { start } = require('./fixtures/apiHarness.cjs');
test('dual-provider REST and WS state use host search/audio and member playlist authorization',async t=>{
  const api=await start();t.after(()=>api.close());
  const call=async(path,id=1,method='GET',body)=>{const response=await fetch(api.origin+'/api'+path,{method,headers:{Authorization:'Bearer '+api.token(id),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return{status:response.status,data:await response.json()};};
  assert.equal((await call('/health')).status,200);
  const room=(await call('/rooms',1,'POST',{name:'Dual music'})).data.room,root='/rooms/'+room.id;
  await call(root+'/join',3,'POST');
  assert.deepEqual((await call(root+'/music/song/search?keywords=test',3)).data.enabledProviders,[]);
  await api.bind(1,'netease');await api.bind(3,'qqmusic');
  assert.equal((await call('/user/qqmusic/playlists',3)).status,200);
  assert.equal((await call('/user/netease/playlists',3)).status,409);
  assert.equal((await call(root+'/playlists',3,'POST',{provider:'qqmusic',playlistId:700})).status,409);
  const raw={id:10,provider:'qqmusic',mid:'forged',name:'Track',artist:'Fixture',duration:180000,prcUrl:''};
  assert.equal((await call(root+'/queue/add',3,'POST',{song:raw})).status,409);
  const single=(await call(root+'/music/song/search?keywords=test',3)).data;
  assert.ok(single.songs.length);assert.ok(single.songs.every(s=>s.provider==='netease'));
  await api.bind(1,'qqmusic');
  const socket = new WebSocket(api.origin.replace('http','ws')); t.after(()=>socket.terminate());
  const frames=[];socket.on('message',raw=>frames.push(JSON.parse(raw)));
  const snapshot=new Promise(resolve=>socket.on('message',raw=>{const e=JSON.parse(raw);if(e.type==='ROOM_SNAPSHOT')resolve(e.payload);}));
  await once(socket,'open');socket.send(JSON.stringify({type:'AUTH',token:api.token(3),roomId:room.id}));
  assert.deepEqual((await snapshot).room.enabledProviders,['netease','qqmusic']);
  const both=(await call(root+'/music/song/search?keywords=test&neteaseOffset=0&qqmusicOffset=0&limit=2',3)).data;
  assert.deepEqual(both.songs.slice(0,2).map(s=>s.provider),['netease','qqmusic']);
  assert.equal(both.songs[0].id,both.songs[1].id);
  const saved=api.qqClient.search; api.qqClient.search=async()=>{throw new Error('private-upstream-token');};
  const partial=(await call(root+'/music/song/search?keywords=test',3)).data; api.qqClient.search=saved;
  assert.ok(partial.songs.length);assert.ok(partial.providers.qqmusic.error);assert.ok(!JSON.stringify(partial).includes('private-upstream-token'));
  const entry=(await call(root+'/playlists',3,'POST',{provider:'qqmusic',playlistId:700})).data;
  assert.equal(entry.state.entries[0].provider,'qqmusic');
  assert.equal((await call(root+'/queue/add',3,'POST',{song:{...raw,id:11}})).status,200);
  const state=(await call(root+'/state',3)).data;
  assert.equal(state.playback.song.provider,'qqmusic');assert.equal(state.playback.song.access,'vip');assert.equal(state.playback.song.trial,true);
  assert.equal(state.playback.song.duration,30000);assert.equal(state.playback.song.lyricOffset,60000);
  await new Promise(resolve=>setImmediate(resolve));
  assert.ok(frames.some(e=>e.type==='PLAY_SONG'&&e.payload.song?.provider==='qqmusic'&&e.payload.song.trial));
  assert.ok((await call(root+'/music/lyric?id=11&provider=qqmusic',3)).data.lyric.includes('QQ'));
  assert.equal((await call(root+'/queue/recommendations/start',3,'POST',{provider:'qqmusic'})).status,403);
  await call(root+'/queue/recommendations/start',1,'POST',{provider:'qqmusic'});
  const playback=(await call(root+'/state')).data.playback;
  await call('/user/qqmusic',1,'DELETE');
  const after=(await call(root+'/state')).data;
  assert.deepEqual(after.playback,playback);assert.equal(after.room.binding.status,'bound');assert.equal(after.room.bindings.qqmusic.status,'unbound');
  assert.ok(after.playlists.entries[0].error);assert.equal(after.recommendations.enabled,false);
  assert.equal((await call(root+'/playlists/'+entry.entryId+'/tracks',3)).status,200);
  assert.equal((await call(root+'/playlists/'+entry.entryId+'/activate',1,'POST')).status,409);
  await api.bind(1,'qqmusic'); assert.equal((await call(root+'/playlists/'+entry.entryId+'/activate',1,'POST')).status,200);
  assert.ok(!JSON.stringify(after).includes('qqmusic_key'));assert.ok(!JSON.stringify(after).includes('CookieEncrypted'));
});
