const { test } = require('node:test');
const assert = require('node:assert/strict');
const { once } = require('node:events');
const WebSocket = require('ws');
const { start } = require('./fixtures/apiHarness.cjs');

test('playlist REST/WS permissions, personal binding, room isolation and snapshots', async t => {
  const api = await start(); t.after(() => api.close());
  const call = async (path, id = 1, method = 'GET', body) => {
    const response = await fetch(api.origin + '/api' + path, { method, headers: { Authorization: 'Bearer ' + api.token(id), 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined });
    return { status: response.status, data: await response.json() };
  };
  const room = (await call('/rooms', 1, 'POST', { name: 'Playlist room' })).data.room;
  const root = '/rooms/' + room.id;
  await call(root + '/join', 3, 'POST');
  const other = (await call('/rooms', 2, 'POST', { name: 'Other room' })).data.room;
  assert.equal((await call('/user/netease/playlists', 3)).status, 409);
  assert.equal((await call('/user/netease/playlists/search?keywords=test', 3)).status, 409);
  assert.equal((await call('/user/netease/playlists/700/tracks?limit=101', 3)).status, 400);
  const qr = (await call('/user/netease/qr', 3, 'POST')).data;
  let bound;
  for (let i = 0; i < 3; i++) bound = (await call('/user/netease/qr/' + qr.sessionId + '/check', 3, 'POST')).data;
  assert.equal(bound.status, 'authorized');
  const personal = await call('/user/netease/playlists?uid=12345', 3);
  assert.equal(personal.status, 200); assert.equal(personal.data.items[0].isLiked, true);
  assert.equal((await call('/user/netease/playlists', 1)).status, 409);
  assert.equal((await call(root + '/playlists', 3, 'POST', { playlistId: 700 })).status, 409);
  await api.bind(1);
  const added = (await call(root + '/playlists', 3, 'POST', { playlistId: 700 })).data;
  assert.equal(added.state.entries[0].addedBy.id, 3); assert.equal(added.state.mode, 'regular');
  assert.ok(!JSON.stringify(added).includes('MUSIC_U')); assert.ok(!JSON.stringify(added).includes('trackIds'));
  assert.equal((await call(root + '/playlists', 1, 'POST', { playlistId: 700 })).data.entryId, added.entryId);
  const entry = root + '/playlists/' + added.entryId;
  const page = (await call(entry + '/tracks?offset=30&limit=30', 1)).data;
  assert.equal(page.items[0].id, 40); assert.equal(page.items.length, 30); assert.equal(page.total, 65);
  assert.equal((await call(entry + '/activate', 3, 'POST')).status, 403);
  assert.equal((await call(entry + '/settings', 3, 'PATCH', { repeat: true })).status, 403);
  assert.equal((await call(entry, 3, 'DELETE')).status, 403);
  assert.equal((await call(root + '/queue/mode', 3, 'POST', { mode: 'playlist' })).status, 403);
  assert.equal((await call(entry + '/next', 3, 'POST', { songId: 40 })).status, 409);

  await call(root + '/queue/add', 3, 'POST', { song: { id: 99, name: 'Manual', artist: 'Fixture', prcUrl: '', duration: 300000 } });
  const socket = new WebSocket(api.origin.replace('http', 'ws'));
  t.after(() => socket.terminate()); const events = []; socket.on('message', raw => events.push(JSON.parse(raw)));
  await once(socket, 'open');
  const snapshot = new Promise(resolve => socket.on('message', raw => { const event = JSON.parse(raw); if (event.type === 'ROOM_SNAPSHOT') resolve(event); }));
  socket.send(JSON.stringify({ type: 'AUTH', token: api.token(3), roomId: room.id }));
  assert.equal((await snapshot).payload.playlists.entries.length, 1);
  const changed = new Promise(resolve => socket.on('message', raw => { const event = JSON.parse(raw); if (event.type === 'PLAYLIST_STATE_UPDATED' && event.payload.mode === 'playlist') resolve(event); }));
  assert.equal((await call(entry + '/activate', 1, 'POST')).status, 200);
  assert.equal((await changed).roomId, room.id);
  const state = (await call(root + '/state', 3)).data;
  assert.equal(state.playback.song.id, 99); assert.equal(state.playlists.mode, 'playlist');
  assert.equal((await call(entry + '/next', 3, 'POST', { songId: 40 })).status, 200);
  await call(root + '/queue/add', 3, 'POST', { song: { id: 88, name: 'Manual later', artist: 'Fixture', prcUrl: '', duration: 300000 } });
  await call(root + '/queue/skipNext', 3, 'POST', { playbackRevision: state.playback.playbackRevision });
  const next = (await call(root + '/state', 3)).data;
  assert.equal(next.playback.song.id, 40); assert.equal(next.playback.song.source, 'playlist');
  assert.equal(next.queue[0].id, 88); assert.equal((await call('/rooms/' + other.id + '/state', 2)).data.playlists.entries.length, 0);
  assert.equal((await call('/rooms/' + other.id + '/playlists/' + added.entryId + '/tracks', 2)).data.code, 'PLAYLIST_NOT_FOUND');
  await call(root + '/leave', 3, 'POST');
  assert.equal((await call(root + '/state')).data.playlists.entries.length, 1);
  assert.equal((await call(entry + '/tracks')).status, 200);
  await call('/user/netease', 3, 'DELETE');
  const invalid = (await call(root + '/state')).data;
  assert.match(invalid.playlists.entries[0].error, /绑定/);
  assert.equal(invalid.playback.song.id, 40);
  await call(entry, 1, 'DELETE'); assert.equal((await call(root + '/state')).data.playlists.entries.length, 0);
});
